name: Create Release Package

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., 1.0.0)'
        required: true
        default: '1.0.0'

permissions:
  contents: write
  actions: read
  id-token: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        
    - name: Scrape fresh data from Archon.gg
      run: |
        echo "🔄 Scraping fresh talent data from Archon.gg..."
        python3 archon_combined_scraper.py
        echo "✅ Data scraping completed"
        
    - name: Create release package
      run: |
        chmod +x create_release.sh
        if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
          ./create_release.sh ${{ github.event.inputs.version }}
        else
          # Extract version from tag
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "Creating release for version: $VERSION"
          ./create_release.sh $VERSION
        fi
        
    - name: List files
      run: |
        echo "Current directory contents:"
        ls -la
        echo "Looking for zip files:"
        ls -la *.zip || echo "No zip files found"
        
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Archon Talents ${{ github.ref_name }}
        body: |
          ## 🎯 Archon Talents v${{ github.ref_name }}
          
          ### ✨ Features
          - Display popular talent builds from Archon.gg
          - Support for both Raid and Mythic+ content
          - Clean, professional interface
          - Minimap button with drag-and-drop support
          
          ### 🚀 Commands
          - `/archon` - Show talent GUI
          - `/archon hide` - Hide talent GUI
          - `/archon hide minimap` - Hide minimap button
          - `/archon show minimap` - Show minimap button
          - `/archon help` - Show help
          
          ### 📦 Installation
          This release is compatible with WowUp and other addon managers.
          
          ### 🔄 Data Updates
          Talent data is automatically updated daily via CI/CD pipeline.
        draft: false
        prerelease: false
        
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./ArchonTalents-${{ github.ref_name }}.zip
        asset_name: ArchonTalents-${{ github.ref_name }}.zip
        asset_content_type: application/zip
