name: Update Archon Talents Builds

on:
  # Run daily at 3:00 AM UTC
  schedule:
    - cron: '0 3 * * *'
  
  # Allow manual triggering
  workflow_dispatch:

jobs:
  update-builds:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        # Use a personal access token for pushing
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
    
    - name: Run build scraper
      run: |
        python archon_combined_scraper.py
    
    - name: Check for changes
      id: changes
      run: |
        if git diff --quiet WCLData.lua; then
          echo "changes=false" >> $GITHUB_OUTPUT
        else
          echo "changes=true" >> $GITHUB_OUTPUT
        fi
    
    - name: Commit and push changes
      if: steps.changes.outputs.changes == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add ArchonData.lua
        git commit -m "Auto-update builds data - $(date '+%Y-%m-%d %H:%M:%S UTC')"
        git push
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-data
        path: |
          ArchonData.lua
          combined_builds.json
          update_builds.log
        retention-days: 30
